### ISSUE TITLE
Channel Suggestion: SMS via Twilio

### ISSUE THREAD

**Issue by conradkleinespel** [RecastAI/bot-connector#2]
Hey everyone !

The bot-connector looks great (thanks for making it open source) and Recast seems to have improved greatly during the last few months (the "Build" UI looks intuitive). So I'm thinking of building a chatbot with Recast to see how it compares to our in-house chatbot :smiley:

We use SMS (via Twilio) at Reassurez-moi.fr because it's a simple way to reach our customers (they don't all have access to messaging apps like WhatsApp, but they all have a mobile phone number).

What do you think of SMS as a communication channel for bots ?

A few things that might need attention:
- how to deal with "Quick Replies" ?
- decoupling the connector from a specific SMS API, or naming it "TwilioSMS" instead of just "SMS" ?

Thanks again !
— Conrad

**Comment by jhoudan** [comment]
Hi Conrad, and thanks for the kind words!

I think it's mandatory to name the Twilio integration 'TwilioSMS' instead of just 'SMS', as other company provides the same service, like Callr.

As for the quick replies, we will have to think carefully about what it implies for a SMS based channel, as there is a notion of cost per message sent and a limit of characters per SMS.
A naive solution can be to concatenate the list of buttons at the end of the SMS, like that:

```
bla bla bla
- choice1
- choice2
- choice3
```

**Comment by conradkleinespel** [comment]
@jhoudan OK ! Thanks for the tips. I'll be working on a simple 1st version of this and post a pull request. I'll update here as I go to keep everyone up to date.

**Comment by conradkleinespel** [comment]
I'm not planning to do this within the next few weeks after all. So if anyone wants to have a go at this, go ! :smiley:

**Comment by jhoudan** [comment]
Twilio is now available :rocket:
